# Generated by Django 3.0 on 2020-01-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='econtact',
            new_name='Emp_contact',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='eemail',
            new_name='Emp_email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='Emp_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ename',
            new_name='Emp_name',
        ),
    ]
