# Generated by Django 3.0 on 2020-01-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200122_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Emp_id',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
